# This is a TOML document. Boom.
title = "App 配置文件"

[app]
AppName = "going"
AppEnv = "debug"
RunMode = "debug"
HttpListen = "0.0.0.0:8022"
GrpcListen = "0.0.0.0:8023"

[mysql]
Dsn = "root:12315Smm@tcp(127.0.0.1:3306)/xthk_payment?charset=utf8&parseTime=True&loc=Local"
MaxIdleConn = 10
MaxOpenConn = 100
ConnMaxLifetime = 2
