# This is a TOML document. Boom.
title = "App 配置文件"

[app]
app_name = "going"
app_env = "debug"
run_mode = "debug"
http_listen = "0.0.0.0:8022"
grpc_listen = "0.0.0.0:8023"

[mysql]
dsn = "root:xthk123456@tcp(192.168.3.100:32106)/xthk_payment?charset=utf8&parseTime=True&loc=Local"
maxIdleConn = 10
maxOpenConn = 100
connMaxLifetime = 2
